bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg]
bitcoin_network = "testnet"

[appcfg.ens]
base_url = "http://ens-service:3339"

[appcfg.challenges]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "eic"
table = "challenges"

[appcfg.email_confirmations]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "eic"
table_confirmations = "email_confirmations"
table_registrations = "email_registrations"

[appcfg.mailjet_config]
sender = "notifications@bit.cr"
url = "https://api.mailjet.com"
api_key = "apikey"
api_secret_key = "secretkey"
logo_url = "https://static.bit.cr/logo.png"
