services:
  eic-service:
    extends:
      file: common-services.yml
      service: eic-service
  ens-service:
    extends:
      file: common-services.yml
      service: ens-service
  surrealdb:
    extends:
      file: common-services.yml
      service: surrealdb
  rproxy:
    extends:
        file: common-services.yml
        service: rproxy
    ports:
      - "4444:4242"
