services:
  eic-service:
    extends:
      file: common-services.yml
      service: eic-service
  ens-service:
    extends:
      file: common-services.yml
      service: ens-service
  relay:
    extends:
      file: common-services.yml
      service: relay
    ports:
      - "8080:8080"
  postgres:
    extends:
      file: common-services.yml
      service: postgres
    ports:
      - "5432:5432"
  surrealdb:
    extends:
      file: common-services.yml
      service: surrealdb
    ports:
      - "8000:8000"
  rproxy:
    extends:
        file: common-services.yml
        service: rproxy
    ports:
      - "4343:4242"
