bind_address = "0.0.0.0:3339"
log_level = "DEBUG"

[appcfg]
host_url = "http://localhost:4343" # the domain where the service is reachable
app_url = "http://localhost:8081" # the domain where the ebill app is hosted for this env

[appcfg.email_notification_preferences]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "ens"
table = "email_notification_preferences"

[appcfg.challenges]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "ens"
table = "challenges"

[appcfg.mailjet_config]
sender = "notifications@bit.cr"
url = "https://api.mailjet.com"
api_key = "apikey"
api_secret_key = "secretkey"
logo_url = "https://static.bit.cr/logo.png"
