bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg.ebill_db]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "ebill"

[appcfg.nostr_cfg]
relays = ["wss://bcr-relay-dev.minibill.tech"]
only_known_contacts = false

[appcfg.mint_config]
default_mint_url = "http://localhost:4343"
default_mint_node_id = "bitcrt039180c169e5f6d7c579cf1cefa37bffd47a2b389c8125601f4068c87bea795943"

[appcfg.court_config]
default_url = "http://localhost:8080"

[appcfg.dev_mode_config]
on = true
disable_mandatory_email_confirmations = true

[appcfg]
bitcoin_network = "testnet"
esplora_base_url = "https://esplora.minibill.tech"
data_dir = "./"
job_runner_initial_delay_seconds = 1
job_runner_check_interval_seconds = 600
url = "https://bitcredit-dev.minibill.tech"

[appcfg.payment_config]
num_confirmations_for_payment = 1

[appcfg.identity_config]
name = "Wildcat0"
email = "info@bitcr.org"
country = "AT"
city = "Vienna"
zip = "1020"
address = "Smithstreet 15, Top 22"
