[package]
name = "bcr-wdc-relay"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum = { workspace = true, features = ["ws", "tokio"] }
axum-raw-websocket = "0.8"
bitcoin.workspace = true
clap = { version = "4.5.39", features = ["derive", "env"] }
deadpool-postgres = "0.14"
futures.workspace = true
nostr = { git = "https://github.com/BitcreditProtocol/nostr.git", rev = "d60e3ebc77c7833db917c3030c145883b8f0ee62", features = ["os-rng"] }
nostr-sdk = { git = "https://github.com/BitcreditProtocol/nostr.git", rev = "d60e3ebc77c7833db917c3030c145883b8f0ee62", features = ["local-relay"] }
base64-url = "3"
nostr-postgres-db = { git = "https://github.com/BitcreditProtocol/nostr-postgres-db.git", rev = "c58d1c922b3f791cb16c6e1767955d05972412ad" }
reqwest = { workspace = true, features = ["stream", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tokio-postgres = { version = "0.7" }
tower-http = { version = "0.7", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
