name: build and push tagged images

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write
  artifact-metadata: write

jobs:
  tagged:
    uses: ./.github/workflows/build-image.yml
    with:
      tags: |
        type=semver,pattern={{version}}
    secrets:
      PRIVATE_REPO_ACCESS_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_REPO_ACCESS_APP_PRIVATE_KEY }}
      GCLOUD_WIF_PROVIDER: ${{ secrets.GCLOUD_WIF_PROVIDER }}
      GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
