name: Test coverage

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read
  security-events: write
  actions: read

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.PRIVATE_REPO_ACCESS_APP_ID }}
          private-key: ${{ secrets.PRIVATE_REPO_ACCESS_APP_PRIVATE_KEY }}
          owner: BitcreditProtocol
      
      - name: Git auth with app token
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          docker system prune -a -f
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          sudo apt-get autoremove -y
          echo "After cleanup:"
          df -h

      - name: Switch rust version
        run: rustup default stable

      - name: Update rust
        run: rustup update stable

      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Activate cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "wildcat-auxiliary"

      - name: Run tests
        run: cargo test --workspace --verbose
        env:
          LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
          RUSTFLAGS: "-Cinstrument-coverage"

      - name: Create coverage report
        run: |
          grcov \
            --source-dir . \
            --binary-path target/debug \
            --branch \
            --excl-start 'mod tests \{' \
            --ignore 'tests/*' \
            --keep-only "crates/*" \
            -o lcov.info \
            -t lcov `find crates -name coverage`

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
